/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/orgs/{orgId}/mcp-servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List MCP servers
         * @description Returns a list of MCP servers for the organization.
         */
        get: operations["listMcpServers"];
        put?: never;
        /**
         * Create MCP server
         * @description Creates a new MCP server.
         */
        post: operations["createMcpServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{orgId}/mcp-servers/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Default MCP server
         * @description Returns the default MCP server for the organization. If not set, it will create a new one.
         */
        get: operations["getDefaultMcpServer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{orgId}/mcp-servers/{mcpServerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete MCP server
         * @description Deletes an MCP server by its ID.
         */
        delete: operations["deleteMcpServer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{orgId}/mcp-servers/{mcpServerId}/sandbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set MCP server to Sandbox
         * @description Sets the specified MCP server to the given Sandbox.
         */
        post: operations["setMcpServerToSandbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{orgId}/sandboxes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sandboxes
         * @description Returns a list of sandboxes for the organization.
         */
        get: operations["listSandboxes"];
        put?: never;
        /**
         * Create Sandbox
         * @description Creates a new sandbox.
         */
        post: operations["createSandbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{orgId}/sandboxes/{sandboxId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sandbox Details
         * @description Get the sandbox details by id
         */
        get: operations["getSandbox"];
        put?: never;
        post?: never;
        /**
         * Delete Sandbox
         * @description Deletes a sandbox by its ID.
         */
        delete: operations["deleteSandbox"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{orgId}/sandboxes/{sandboxId}/actions/computer-use": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute Computer Use Action
         * @description Executes a computer use action on the sandbox.
         */
        post: operations["executeComputerUseAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{orgId}/sandboxes/{sandboxId}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Sandbox
         * @description Takes a screenshot and gets cursor position of the sandbox.
         */
        post: operations["previewSandbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{orgId}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description Returns a list of projects for the organization.
         */
        get: operations["listProjects"];
        put?: never;
        /**
         * Create Project
         * @description Creates a new project.
         */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{orgId}/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Project
         * @description Deletes a project by its ID.
         */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/computer-use/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse LLM Output
         * @description Parses the output text of computer use model and returns the parsed actions.
         */
        post: operations["parseModelOutput"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{orgId}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Organization Stats
         * @description Returns the stats of the organization, such as number of members, computers, etc.
         */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ListMcpServerResponse: {
            /** @description ID of the MCP server. */
            id: string;
            /** @description Name of the MCP server. */
            name: string;
            /** @description Creation date of the MCP server. */
            createdAt: string;
            /** @description Whether this is the default MCP server for the organization. */
            defaultMcpServer: boolean;
            /** @description Project ID to which the MCP server belongs. */
            projectId: string;
            policy: {
                /**
                 * @description The maximum lifetime of a sandbox.
                 * @default 3600
                 */
                sandboxMaxLifetimeSeconds: number;
                /**
                 * @description The maximum idle time of a sandbox.
                 * @default 3600
                 */
                sandboxMaxIdleTimeSeconds: number;
                /**
                 * @description Whether to create a new sandbox automatically when old sandbox is deleted. If not, new sandboxes will be created when calling computer use tools.
                 * @default false
                 */
                sandboxAutoCreation: boolean;
                /**
                 * @description Whether to expose recreate tool to LLMs.
                 * @default false
                 */
                sandboxExposeRecreateTool: boolean;
                /**
                 * @description Whether to expose restart tool to LLMs.
                 * @default false
                 */
                sandboxExposeRestartTool: boolean;
                /**
                 * @description Whether to expose delete tool to LLMs.
                 * @default false
                 */
                sandboxExposeDeleteTool: boolean;
            };
            /** @description ID of the currently connected sandbox. */
            currentSandboxId: string | null;
        }[];
        McpServerResponseDto: {
            /** @description ID of the MCP server. */
            id: string;
            /** @description Name of the MCP server. */
            name: string;
            /** @description Creation date of the MCP server. */
            createdAt: string;
            /** @description Whether this is the default MCP server for the organization. */
            defaultMcpServer: boolean;
            /** @description Project ID to which the MCP server belongs. */
            projectId: string;
            policy: {
                /**
                 * @description The maximum lifetime of a sandbox.
                 * @default 3600
                 */
                sandboxMaxLifetimeSeconds: number;
                /**
                 * @description The maximum idle time of a sandbox.
                 * @default 3600
                 */
                sandboxMaxIdleTimeSeconds: number;
                /**
                 * @description Whether to create a new sandbox automatically when old sandbox is deleted. If not, new sandboxes will be created when calling computer use tools.
                 * @default false
                 */
                sandboxAutoCreation: boolean;
                /**
                 * @description Whether to expose recreate tool to LLMs.
                 * @default false
                 */
                sandboxExposeRecreateTool: boolean;
                /**
                 * @description Whether to expose restart tool to LLMs.
                 * @default false
                 */
                sandboxExposeRestartTool: boolean;
                /**
                 * @description Whether to expose delete tool to LLMs.
                 * @default false
                 */
                sandboxExposeDeleteTool: boolean;
            };
            /** @description ID of the currently connected sandbox. */
            currentSandboxId: string | null;
        };
        CreateMcpServerDto: {
            /** @description Name of the MCP server. */
            name: string;
            /** @description Project to which the MCP server belongs to. */
            projectId?: string;
            /**
             * @description The maximum lifetime of a sandbox.
             * @default 3600
             */
            sandboxMaxLifetimeSeconds: number;
            /**
             * @description The maximum idle time of a sandbox.
             * @default 3600
             */
            sandboxMaxIdleTimeSeconds: number;
            /**
             * @description Whether to create a new sandbox automatically when old sandbox is deleted. If not, new sandboxes will be created when calling computer use tools.
             * @default false
             */
            sandboxAutoCreation: boolean;
            /**
             * @description Whether to expose recreate tool to LLMs.
             * @default false
             */
            sandboxExposeRecreateTool: boolean;
            /**
             * @description Whether to expose restart tool to LLMs.
             * @default false
             */
            sandboxExposeRestartTool: boolean;
            /**
             * @description Whether to expose delete tool to LLMs.
             * @default false
             */
            sandboxExposeDeleteTool: boolean;
        };
        SetMcpServerToSandboxResponseDto: {
            /** @description The ID of the sandbox to connect the MCP server to. */
            sandboxId: string | null;
        };
        SandboxListResponseDto: {
            id: string;
            name: string;
            expiredAt: unknown;
            createdAt: unknown;
            projectId: string;
        }[];
        CreateSandboxDto: {
            /**
             * @description The name of the sandbox.
             * @default sandbox
             */
            name: string;
            /**
             * @description The maximum life time of the sandbox in seconds. Default is 1 hour, max is 1 day.
             * @default 3600
             */
            maxLifeSeconds: number;
            /** @description The project id to use for the sandbox. Use default if not provided. */
            projectId?: string;
            /** @description The spec of the sandbox. Use default if not provided. */
            specId?: string;
            /** @description The datacenter id to use for the sandbox. Use default if not provided. */
            datacenterId?: string;
        };
        GetSandboxResponseDto: {
            sandbox: {
                id: string;
                name: string;
                expiredAt: unknown;
                createdAt: unknown;
                projectId: string;
            };
            connectDetails: {
                gatewayAddresses: {
                    address: string;
                    port: number;
                    name: string;
                    preferredProviders: ("CHINA_TELECOM" | "CHINA_UNICOM" | "CHINA_MOBILE" | "GLOBAL_BGP" | 1 | 2 | 3 | 4)[];
                    /** @enum {string} */
                    gatewayType: "KCP" | "QUIC" | "WEB_TRANSPORT" | 4 | 5 | 6;
                }[];
                certificateHashBase64: string;
                endUserToken: string;
                roomId: string;
            };
        };
        ComputerUseActionDto: {
            /** @description All possible computer use actions, with optional callId */
            action: {
                /** @description Optional call identifier */
                callId?: string;
            } & ({
                /** @enum {string} */
                type: "mouse:click";
                /** @description X coordinate */
                x: {
                    /**
                     * @description Indicates the unit is pixel
                     * @enum {string}
                     */
                    type: "px";
                    /** @description Length in pixels */
                    value: number;
                } | {
                    /** @enum {string} */
                    type: "/";
                    /** @description Numerator of the fraction */
                    numerator: number;
                    /** @description Denominator of the fraction */
                    denominator: number;
                };
                /** @description Y coordinate */
                y: {
                    /**
                     * @description Indicates the unit is pixel
                     * @enum {string}
                     */
                    type: "px";
                    /** @description Length in pixels */
                    value: number;
                } | {
                    /** @enum {string} */
                    type: "/";
                    /** @description Numerator of the fraction */
                    numerator: number;
                    /** @description Denominator of the fraction */
                    denominator: number;
                };
                /** @description Mouse button flag combination. 1: left, 2: right, 4: middle, 8: back, 16: forward; add them together to press multiple buttons at once. */
                button: number;
                /** @description Key to hold down during click, in xdotool key syntax. Example: "ctrl", "alt", "alt+shift". */
                holdKey?: string;
            } | {
                /** @enum {string} */
                type: "mouse:doubleClick";
                /** @description X coordinate */
                x: {
                    /**
                     * @description Indicates the unit is pixel
                     * @enum {string}
                     */
                    type: "px";
                    /** @description Length in pixels */
                    value: number;
                } | {
                    /** @enum {string} */
                    type: "/";
                    /** @description Numerator of the fraction */
                    numerator: number;
                    /** @description Denominator of the fraction */
                    denominator: number;
                };
                /** @description Y coordinate */
                y: {
                    /**
                     * @description Indicates the unit is pixel
                     * @enum {string}
                     */
                    type: "px";
                    /** @description Length in pixels */
                    value: number;
                } | {
                    /** @enum {string} */
                    type: "/";
                    /** @description Numerator of the fraction */
                    numerator: number;
                    /** @description Denominator of the fraction */
                    denominator: number;
                };
                /** @description Mouse button index */
                button: number;
                /** @description Key to hold down during double click, in xdotool key syntax. Example: "ctrl", "alt", "alt+shift". */
                holdKey?: string;
            } | {
                /** @enum {string} */
                type: "mouse:move";
                /** @description X coordinate */
                x: {
                    /**
                     * @description Indicates the unit is pixel
                     * @enum {string}
                     */
                    type: "px";
                    /** @description Length in pixels */
                    value: number;
                } | {
                    /** @enum {string} */
                    type: "/";
                    /** @description Numerator of the fraction */
                    numerator: number;
                    /** @description Denominator of the fraction */
                    denominator: number;
                };
                /** @description Y coordinate */
                y: {
                    /**
                     * @description Indicates the unit is pixel
                     * @enum {string}
                     */
                    type: "px";
                    /** @description Length in pixels */
                    value: number;
                } | {
                    /** @enum {string} */
                    type: "/";
                    /** @description Numerator of the fraction */
                    numerator: number;
                    /** @description Denominator of the fraction */
                    denominator: number;
                };
                /** @description Key to hold down during move, in xdotool key syntax. Example: "ctrl", "alt", "alt+shift". */
                holdKey?: string;
            } | {
                /** @enum {string} */
                type: "mouse:scroll";
                /** @description X coordinate */
                x: {
                    /**
                     * @description Indicates the unit is pixel
                     * @enum {string}
                     */
                    type: "px";
                    /** @description Length in pixels */
                    value: number;
                } | {
                    /** @enum {string} */
                    type: "/";
                    /** @description Numerator of the fraction */
                    numerator: number;
                    /** @description Denominator of the fraction */
                    denominator: number;
                };
                /** @description Y coordinate */
                y: {
                    /**
                     * @description Indicates the unit is pixel
                     * @enum {string}
                     */
                    type: "px";
                    /** @description Length in pixels */
                    value: number;
                } | {
                    /** @enum {string} */
                    type: "/";
                    /** @description Numerator of the fraction */
                    numerator: number;
                    /** @description Denominator of the fraction */
                    denominator: number;
                };
                /** @description Vertical scroll steps */
                stepVertical: number;
                /** @description Horizontal scroll steps */
                stepHorizontal: number;
                /** @description Key to hold down during scroll, in xdotool key syntax. Example: "ctrl", "alt", "alt+shift". */
                holdKey?: string;
            } | {
                /** @enum {string} */
                type: "mouse:drag";
                /** @description Start X coordinate */
                startX: {
                    /**
                     * @description Indicates the unit is pixel
                     * @enum {string}
                     */
                    type: "px";
                    /** @description Length in pixels */
                    value: number;
                } | {
                    /** @enum {string} */
                    type: "/";
                    /** @description Numerator of the fraction */
                    numerator: number;
                    /** @description Denominator of the fraction */
                    denominator: number;
                };
                /** @description Start Y coordinate */
                startY: {
                    /**
                     * @description Indicates the unit is pixel
                     * @enum {string}
                     */
                    type: "px";
                    /** @description Length in pixels */
                    value: number;
                } | {
                    /** @enum {string} */
                    type: "/";
                    /** @description Numerator of the fraction */
                    numerator: number;
                    /** @description Denominator of the fraction */
                    denominator: number;
                };
                /** @description End X coordinate */
                endX: {
                    /**
                     * @description Indicates the unit is pixel
                     * @enum {string}
                     */
                    type: "px";
                    /** @description Length in pixels */
                    value: number;
                } | {
                    /** @enum {string} */
                    type: "/";
                    /** @description Numerator of the fraction */
                    numerator: number;
                    /** @description Denominator of the fraction */
                    denominator: number;
                };
                /** @description End Y coordinate */
                endY: {
                    /**
                     * @description Indicates the unit is pixel
                     * @enum {string}
                     */
                    type: "px";
                    /** @description Length in pixels */
                    value: number;
                } | {
                    /** @enum {string} */
                    type: "/";
                    /** @description Numerator of the fraction */
                    numerator: number;
                    /** @description Denominator of the fraction */
                    denominator: number;
                };
                /** @description Key to hold down during drag, in xdotool key syntax. Example: "ctrl", "alt", "alt+shift". */
                holdKey?: string;
            } | {
                /** @enum {string} */
                type: "keyboard:type";
                /** @description Text content to type */
                content: string;
                /**
                 * @description Whether to treat line breaks as enter. If true, any line breaks(\n) in content will be treated as enter key press, and content will be split into multiple lines.
                 * @default false
                 */
                treatNewLineAsEnter: boolean | null;
            } | {
                /** @enum {string} */
                type: "keyboard:hotkey";
                /** @description Hotkey combination, in xdotool key syntax. Examples: "a", "Return", "alt+Tab", "ctrl+s", "Up", "KP_0" (for the numpad 0 key). */
                keys: string;
                /** @description Duration in milliseconds. If specified, the hotkey will be held for a while and then released. */
                duration?: number;
            } | {
                /** @enum {string} */
                type: "screenshot";
            } | {
                /** @enum {string} */
                type: "wait";
                /** @description Duration in milliseconds */
                duration: number;
            } | {
                /** @enum {string} */
                type: "finished";
                /** @description Completion message */
                message?: string;
            } | {
                /** @enum {string} */
                type: "failed";
                /** @description Failure message */
                message?: string;
            });
            /**
             * @description Whether to include the screenshot url after action in the response
             * @default true
             */
            includeScreenShot: boolean;
            /**
             * @description Whether to include the cursor position after action in the response
             * @default true
             */
            includeCursorPosition: boolean;
        };
        SandboxActionResponseDto: {
            /**
             * Format: uri
             * @description The screenshot of the sandbox after the action is executed.
             */
            screenShot?: string;
            cursorPosition?: {
                /** @description The x position of the cursor. */
                x: number;
                /** @description The y position of the cursor. */
                y: number;
                /** @description The width of the screen. */
                screenWidth: number;
                /** @description The height of the screen. */
                screenHeight: number;
                /** @description The index of the screen. */
                screenIndex: number;
            };
        };
        ListProjectsResponseDto: {
            id: string;
            name: string;
            createdAt: string;
            defaultProject: boolean;
        }[];
        CreateProjectDto: {
            /** @description Name of the project. */
            name: string;
        };
        SingleProjectResponseDto: {
            id: string;
            name: string;
            createdAt: string;
            defaultProject: boolean;
        };
        ComputerUseParseRequestDto: {
            /**
             * @description The model to parse the input for
             * @enum {string}
             */
            model: "ui-tars" | "oai-compute-use";
            /** @description The text content to parse */
            textContent: string;
        };
        ComputerUseActionResponseDto: {
            actions: ({
                /** @description Optional call identifier */
                callId?: string;
            } & ({
                /** @enum {string} */
                type: "mouse:click";
                /** @description X coordinate */
                x: {
                    /**
                     * @description Indicates the unit is pixel
                     * @enum {string}
                     */
                    type: "px";
                    /** @description Length in pixels */
                    value: number;
                } | {
                    /** @enum {string} */
                    type: "/";
                    /** @description Numerator of the fraction */
                    numerator: number;
                    /** @description Denominator of the fraction */
                    denominator: number;
                };
                /** @description Y coordinate */
                y: {
                    /**
                     * @description Indicates the unit is pixel
                     * @enum {string}
                     */
                    type: "px";
                    /** @description Length in pixels */
                    value: number;
                } | {
                    /** @enum {string} */
                    type: "/";
                    /** @description Numerator of the fraction */
                    numerator: number;
                    /** @description Denominator of the fraction */
                    denominator: number;
                };
                /** @description Mouse button flag combination. 1: left, 2: right, 4: middle, 8: back, 16: forward; add them together to press multiple buttons at once. */
                button: number;
                /** @description Key to hold down during click, in xdotool key syntax. Example: "ctrl", "alt", "alt+shift". */
                holdKey?: string;
            } | {
                /** @enum {string} */
                type: "mouse:doubleClick";
                /** @description X coordinate */
                x: {
                    /**
                     * @description Indicates the unit is pixel
                     * @enum {string}
                     */
                    type: "px";
                    /** @description Length in pixels */
                    value: number;
                } | {
                    /** @enum {string} */
                    type: "/";
                    /** @description Numerator of the fraction */
                    numerator: number;
                    /** @description Denominator of the fraction */
                    denominator: number;
                };
                /** @description Y coordinate */
                y: {
                    /**
                     * @description Indicates the unit is pixel
                     * @enum {string}
                     */
                    type: "px";
                    /** @description Length in pixels */
                    value: number;
                } | {
                    /** @enum {string} */
                    type: "/";
                    /** @description Numerator of the fraction */
                    numerator: number;
                    /** @description Denominator of the fraction */
                    denominator: number;
                };
                /** @description Mouse button index */
                button: number;
                /** @description Key to hold down during double click, in xdotool key syntax. Example: "ctrl", "alt", "alt+shift". */
                holdKey?: string;
            } | {
                /** @enum {string} */
                type: "mouse:move";
                /** @description X coordinate */
                x: {
                    /**
                     * @description Indicates the unit is pixel
                     * @enum {string}
                     */
                    type: "px";
                    /** @description Length in pixels */
                    value: number;
                } | {
                    /** @enum {string} */
                    type: "/";
                    /** @description Numerator of the fraction */
                    numerator: number;
                    /** @description Denominator of the fraction */
                    denominator: number;
                };
                /** @description Y coordinate */
                y: {
                    /**
                     * @description Indicates the unit is pixel
                     * @enum {string}
                     */
                    type: "px";
                    /** @description Length in pixels */
                    value: number;
                } | {
                    /** @enum {string} */
                    type: "/";
                    /** @description Numerator of the fraction */
                    numerator: number;
                    /** @description Denominator of the fraction */
                    denominator: number;
                };
                /** @description Key to hold down during move, in xdotool key syntax. Example: "ctrl", "alt", "alt+shift". */
                holdKey?: string;
            } | {
                /** @enum {string} */
                type: "mouse:scroll";
                /** @description X coordinate */
                x: {
                    /**
                     * @description Indicates the unit is pixel
                     * @enum {string}
                     */
                    type: "px";
                    /** @description Length in pixels */
                    value: number;
                } | {
                    /** @enum {string} */
                    type: "/";
                    /** @description Numerator of the fraction */
                    numerator: number;
                    /** @description Denominator of the fraction */
                    denominator: number;
                };
                /** @description Y coordinate */
                y: {
                    /**
                     * @description Indicates the unit is pixel
                     * @enum {string}
                     */
                    type: "px";
                    /** @description Length in pixels */
                    value: number;
                } | {
                    /** @enum {string} */
                    type: "/";
                    /** @description Numerator of the fraction */
                    numerator: number;
                    /** @description Denominator of the fraction */
                    denominator: number;
                };
                /** @description Vertical scroll steps */
                stepVertical: number;
                /** @description Horizontal scroll steps */
                stepHorizontal: number;
                /** @description Key to hold down during scroll, in xdotool key syntax. Example: "ctrl", "alt", "alt+shift". */
                holdKey?: string;
            } | {
                /** @enum {string} */
                type: "mouse:drag";
                /** @description Start X coordinate */
                startX: {
                    /**
                     * @description Indicates the unit is pixel
                     * @enum {string}
                     */
                    type: "px";
                    /** @description Length in pixels */
                    value: number;
                } | {
                    /** @enum {string} */
                    type: "/";
                    /** @description Numerator of the fraction */
                    numerator: number;
                    /** @description Denominator of the fraction */
                    denominator: number;
                };
                /** @description Start Y coordinate */
                startY: {
                    /**
                     * @description Indicates the unit is pixel
                     * @enum {string}
                     */
                    type: "px";
                    /** @description Length in pixels */
                    value: number;
                } | {
                    /** @enum {string} */
                    type: "/";
                    /** @description Numerator of the fraction */
                    numerator: number;
                    /** @description Denominator of the fraction */
                    denominator: number;
                };
                /** @description End X coordinate */
                endX: {
                    /**
                     * @description Indicates the unit is pixel
                     * @enum {string}
                     */
                    type: "px";
                    /** @description Length in pixels */
                    value: number;
                } | {
                    /** @enum {string} */
                    type: "/";
                    /** @description Numerator of the fraction */
                    numerator: number;
                    /** @description Denominator of the fraction */
                    denominator: number;
                };
                /** @description End Y coordinate */
                endY: {
                    /**
                     * @description Indicates the unit is pixel
                     * @enum {string}
                     */
                    type: "px";
                    /** @description Length in pixels */
                    value: number;
                } | {
                    /** @enum {string} */
                    type: "/";
                    /** @description Numerator of the fraction */
                    numerator: number;
                    /** @description Denominator of the fraction */
                    denominator: number;
                };
                /** @description Key to hold down during drag, in xdotool key syntax. Example: "ctrl", "alt", "alt+shift". */
                holdKey?: string;
            } | {
                /** @enum {string} */
                type: "keyboard:type";
                /** @description Text content to type */
                content: string;
                /**
                 * @description Whether to treat line breaks as enter. If true, any line breaks(\n) in content will be treated as enter key press, and content will be split into multiple lines.
                 * @default false
                 */
                treatNewLineAsEnter: boolean | null;
            } | {
                /** @enum {string} */
                type: "keyboard:hotkey";
                /** @description Hotkey combination, in xdotool key syntax. Examples: "a", "Return", "alt+Tab", "ctrl+s", "Up", "KP_0" (for the numpad 0 key). */
                keys: string;
                /** @description Duration in milliseconds. If specified, the hotkey will be held for a while and then released. */
                duration?: number;
            } | {
                /** @enum {string} */
                type: "screenshot";
            } | {
                /** @enum {string} */
                type: "wait";
                /** @description Duration in milliseconds */
                duration: number;
            } | {
                /** @enum {string} */
                type: "finished";
                /** @description Completion message */
                message?: string;
            } | {
                /** @enum {string} */
                type: "failed";
                /** @description Failure message */
                message?: string;
            }))[];
        };
        StatsResponseDto: {
            /** @description Number of MCP servers */
            mcpServers: number;
            /** @description Number of sandboxes */
            sandboxes: number;
            /** @description Number of projects */
            projects: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listMcpServers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The organization ID */
                orgId: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMcpServerResponse"];
                };
            };
        };
    };
    createMcpServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The organization ID */
                orgId: unknown;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMcpServerDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpServerResponseDto"];
                };
            };
        };
    };
    getDefaultMcpServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The organization ID */
                orgId: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpServerResponseDto"];
                };
            };
        };
    };
    deleteMcpServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mcpServerId: string;
                /** @description The organization ID */
                orgId: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setMcpServerToSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mcpServerId: string;
                /** @description The organization ID */
                orgId: unknown;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetMcpServerToSandboxResponseDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listSandboxes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The organization ID */
                orgId: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxListResponseDto"];
                };
            };
        };
    };
    createSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The organization ID */
                orgId: unknown;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSandboxDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetSandboxResponseDto"];
                };
            };
        };
    };
    getSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sandboxId: string;
                /** @description The organization ID */
                orgId: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetSandboxResponseDto"];
                };
            };
        };
    };
    deleteSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sandboxId: string;
                /** @description The organization ID */
                orgId: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    executeComputerUseAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sandboxId: string;
                /** @description The organization ID */
                orgId: unknown;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComputerUseActionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxActionResponseDto"];
                };
            };
        };
    };
    previewSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sandboxId: string;
                /** @description The organization ID */
                orgId: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxActionResponseDto"];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The organization ID */
                orgId: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListProjectsResponseDto"];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The organization ID */
                orgId: unknown;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SingleProjectResponseDto"];
                };
            };
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                /** @description The organization ID */
                orgId: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    parseModelOutput: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComputerUseParseRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComputerUseActionResponseDto"];
                };
            };
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The organization ID */
                orgId: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponseDto"];
                };
            };
        };
    };
}
